[build]
  base = "/"
  command = "npm run build"
  publish = "/opt/build/repo/out"
[build.environment]
  NODE_VERSION = "18"
[functions]
  external_node_modules = ["express", "mongodb"]
  node_bundler = "esbuild"
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"
[[redirects]]
  from = "/*"
  status = 200
  to = "/index.html"

# Netlify Next.js plugin configuration
[[plugins]]
  package = "@netlify/plugin-nextjs"
  [plugins.inputs]
    publishDir = "/opt/build/repo/out"
