name: Build and upload docker image
on:
  pull_request:
    branches:
      - "main"
      - "coding-for-home-page"
  push:
    branches:
      - '**'

      
jobs:
  build-upload:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v3


      - name: Set up Node.js
        uses: actions/setup-node@v3
        with: 
            node-version: '20'

      
      - name: Check if docker available or not
        run : which docker
      

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: build frontend
        run : docker build -t nimto-fe:$(git log -1 --pretty=format:%h) ./frontend
      
      - name: build backend
        run: docker build -t nimto-be:$(git log -1 --pretty=format:%h) ./backend
      - name: upload docker images
        run: |
          docker images
          
          docker tag nimto-fe:$(git log -1 --pretty=format:%h) ${{ vars.DOCKERHUB_NIMTO_FE }}:$(git log -1 --pretty=format:%h)
          docker tag nimto-be:$(git log -1 --pretty=format:%h) ${{ vars.DOCKERHUB_NIMTO_BE }}:$(git log -1 --pretty=format:%h) 

      
          

          # push
          docker push ${{ vars.DOCKERHUB_NIMTO_FE }}:$(git log -1 --pretty=format:%h)
          docker push ${{ vars.DOCKERHUB_NIMTO_BE }}:$(git log -1 --pretty=format:%h)
  # deploy:
  #   runs-on: ubuntu-latest
  #   environment: ${{ github.ref_name }}
  #   needs: build-upload
  #   steps:
  #     - uses: actions/checkout@v3
      
  #     - uses: aws-actions/configure-aws-credentials@v4
  #       with:
  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         aws-region: us-east-1
  #     - name: Setup Terraform
  #       uses: hashicorp/setup-terraform@v2
  #       with:
  #         terraform_wrapper: false 
  #     - name: create ec2 instance
  #       working-directory: .github/IaC
  #       run: |
  #         terraform init
  #         terraform validate
  #         terraform plan
  #         terraform apply -auto-approve
   
  #     - name: update nimto
  #       working-directory: .github/scripts
  #       run: | 
  #         sudo apt-get update
  #         sudo apt-get install -y expect
  #         echo updating app
  #         public_ip=$(aws ec2 describe-instances --filters "Name=tag-value,Values=mern-instance" --query "Reservations[*].Instances[*].PublicIpAddress" --output text)
  #         sleep 10
  #         ./deploy.sh $public_ip
